routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




/*
 * Front End Routes
 */
Route::get('/search/','SearchController@index')->name('search.index');

Route::get('/contact/','PageController@contact')->name('contact.index');
Route::get('/usloviq/','PageController@usloviq')->name('usloviq.index');
Route::get('/gdpr/','PageController@gdpr')->name('gdpr.index');

Route::get('/ads/gradove/','RegionController@index')->name('region.index');
Route::get('/ads/gradove/{id}/{slug}','RegionController@single')->name('region.single');
Route::get('/','HomeController@index')->name('home');
Route::get('/ads','AdController@index')->name('ad.index');

Route::get('/ads/kategorii','CategoryController@index')->name('category.index');
Route::get('/ads/kategorii/{id}/{slug}', 'CategoryController@single')->name('category.single');
Route::get('/ads/tip/{id}/{slug}', 'AdTypeController@index')->name('adtype.single');

Route::get('users', 'UserController@index')->name('users.index');
Route::get('users/ads/{id}', 'UserController@publishedads')->name('users.publishedads');

Route::get('users/{id}', 'UserController@single')->name('users.single');
Route::get('ratings/user/{id}', 'RatingController@single')->name('ratings.single');

Route::get('/ads/{id}/{catslug}/{uid}','AdController@single')->name('ad.single');




//blog

Route::get('articles', 'BlogArticleController@index')->name('articles.index');
Route::get('articles/read/{article_id}/{category_slug}/{article_slug}/', 'BlogArticleController@single')->name('blogarticles.single');

Route::get('articles/category/{category_id}/{category-slug}', 'BlogCategoryController@single')->name('blogcategories.single');


//end blog


Route::group(['middleware' => 'auth'], function() {
    //Auth routes for the front end
    Route::post('dashboard/edit', 'DashboardController@storeprofile')->name('store.profile');
    Route::get('ads/create', 'AdController@create')->name('ad.create');
    Route::post('ads/store', 'AdController@store')->name('ad.store');
    Route::get('ads/edit/{id}', 'AdController@edit')->name('ad.edit')->middleware('isYourAd');
    Route::get('ads/editimages/{id}', 'AdController@editimages')->name('ad.editimages')->middleware('isYourAd');
    Route::post('ads/update/{id}', 'AdController@update')->name('ad.update')->middleware('isYourAd');
    Route::post('ads/deleteimage/{id}', 'AdController@deleteimage')->name('adimage.delete')->middleware('isYourAd');;
    Route::post('ads/updateimage/{id}', 'AdController@updateimage')->name('adimage.update')->middleware('isYourAd');;


    Route::post('favoriteads/{ad_id}', 'FavoriteAdsController@store')->name('favorite.store');
    Route::post('deletefavoriteads/{id}', 'FavoriteAdsController@destroy')->name('favorite.destroy');

    Route::get('dashboard/favorites', 'FavoriteAdsController@index')->name('dashboard.favorites');
    Route::get('report/{id}', 'ReportController@create')->name('report.create');
    Route::post('report/{id}', 'ReportController@store')->name('report.store');
//    Route::get('uploadimage', 'AdController@mainimage')->name('ad.mainimage');
    Route::get('offer/{ad_id}', 'OfferController@create')->name('offer.create');
    Route::post('offer/{ad_id}', 'OfferController@store')->name('offer.store');
    Route::get('offers/', 'OfferController@index')->name('offer.index');
    Route::get('offer/read/{id}', 'OfferController@single')->name('offer.single');
    Route::get('dashboard/myads', 'DashboardController@myads')->name('dashboard.myads');
    Route::get('messages', 'MessageController@index')->name('messages.index');
    Route::get('messages/read/{id}', 'MessageController@single')->name('messages.single');
    Route::post('messages/insert/{id}', 'MessageController@insert')->name('messages.insert');
    Route::post('messages/compose/{adid}/{sender_id}/{receiver?}', 'MessageController@create')->name('messages.create');
    Route::get('messages/create/{adid}/{sender_id}/{accept?}', 'MessageController@compose')->name('messages.compose');
    Route::post('offerreject/{id}', 'OfferController@reject')->name('offer.reject');
    Route::post('acceptoffer/{id}', 'OfferController@accept')->name('offer.accept');
    Route::get('dashboard/changepassword', 'UserController@changepassword')->name('user.changepassword');
    Route::get('dashboard/editprofile', 'DashboardController@editprofile')->name('dashboard.editprofile');
    Route::post('dashboard/changepassword', 'UserController@updatepassword')->name('dashboard.updatepassword');
    Route::get('offer/activeoffers/{id}', 'OfferController@activesingle')->name('offer.activesingle');
    Route::post('offer/activeoffers/{id}', 'OfferController@finishoffer')->name('offer.finishoffer');

    Route::post('/ratings/{id}/','RatingController@store')->name('rating.store');






});
Auth::routes(['verify' => true]);






Auth::routes();

Route::get('/blog', function () {
    return view('blog.index');
});

Route::get('logout', 'Auth\LoginController@logout');


//Auth::routes(['verify' => true]);

//Route::get('/home', 'HomeController@index')->name('home');

/*
 * admin routes
 */



Route::namespace('Admin')->prefix('panel')->name('admin.')->middleware('admin')->group(function () {

    Route::resource('region','RegionController');
    Route::resource('adtype','AdTypeController');
    Route::resource('ad','AdController');
    Route::resource('adcondition','AdConditionController');
    Route::resource('addelivery','AdDeliveryController');
    Route::resource('ad','AdController');
    Route::resource('category','CategoryController');
    Route::resource('settings','SettingsController');
    Route::resource('messages','MessageController');
    Route::resource('reports','ReportController');
    Route::resource('blogarticles','BlogArticleController');
    Route::resource('blogcategories','BlogCategoryController');
    Route::resource('statictexts','StaticTextController');
    Route::resource('pages','PagesController');
    Route::resource('users','UserController');
    Route::resource('offers','OfferController');
    Route::resource('ratings','RatingController');
    Route::get('/panel', function () {
        return view('admin.layouts.app');
    })->name('panel.welcome');



});

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use App\Ad;
use App\AdCondition;
use App\AdDelivery;
use App\AdImage;
use App\AdType;
use App\Category;
use App\Conversation;
use App\FavoriteAds;
use App\Region;
use App\User;
use Faker\Provider\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Requests\CreateAdRequest;
use App\Http\Requests\UpdateImageRequest;

use Illuminate\Support\Facades\Auth;

class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads = Ad::with('type','category','user','condition','delivery'
        )->where('is_active',true)
        ->orderBy('created_at','desc')
        ->paginate(8);

        return view('ads.index',compact('ads'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $adtypes = AdType::all();
        $adconditions = AdCondition::all();
        $addeliveries = AdDelivery::all();
        $regions = Region::all();
        $categories = Category::with('parent','children')->get();

        return view('ads.create',
            compact('adtypes','adconditions','addeliveries','regions','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateAdRequest $request)
    {


        $data = $request->validated();
//        dd($data);
        $ad = new Ad;
        $ad->adtype_id = $data['adtype_id'];
        $ad->title = $data['title'];
        $ad->description = $data['description'];
        $ad->price = $data['price'];
        if($data['category_id'] == null) {
            $ad->category_id = $data['main_category'];
        }
        else {
            $ad->category_id = $data['category_id'];
        }
        $ad->adcondition_id = $data['adcondition_id'];
        $ad->addelivery_id = $data['addelivery_id'];
        $ad->region_id = $data['region_id'];
        $string = strtolower(str_random(7));
       $ad->uid = $string;
       $ad->views = 1;
       $ad->user_id =  Auth::id();
        $ad->accept_offers = $data['accept_offer'];

       $ad->save();
        if($ad->wasRecentlyCreated) {

            if(array_key_exists('images',$data)) {
                    $counter = 1;
                    foreach ($data['images'] as $file) {
                        $extension = $file->getClientOriginalExtension();
                        $fileName = str_random(5)."-".date('his')."-".str_random(3).".".$extension;
                        $folderpath  = 'uploads/obqvi/'.$ad->uid . '/';
                         $test =  $file->move($folderpath , $fileName);
                         $filepath =  $folderpath . $fileName;

                         $dbimages = new AdImage();
                         $dbimages->ad_id = $ad->id;
                         $dbimages->filepath = $filepath;
                         if($counter == 1) {
                             $dbimages->is_first = true;
                         }
                         $dbimages->save();
                         $counter++;

                    }

            }
            else {
                $dbimages = new AdImage();
                $dbimages->ad_id = $ad->id;
                $dbimages->is_first = true;
                $dbimages->filepath = 'noimage-small.png';

                $dbimages->save();

            }

        }

        return redirect()->route('ad.single',['id' => $ad->id,'catslug'=> $ad->category->slug,'uid' => $ad->uid])->with
    ('info','Обявата е успешно публикувана');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
public function  updateimage($id, UpdateImageRequest $request) {
    $data = $request->validated();

    $ad = Ad::find($id);
    if($ad->images->count() >= 6) {
        return back()->with('message','Вече има качени 6 изображения');
    }

    if($data['images']) {

        $counter = 1;
        foreach ($data['images'] as $file) {
            if($counter == 6) {
                break;
            }

            $extension = $file->getClientOriginalExtension();
            $fileName = str_random(5)."-".date('his')."-".str_random(3).".".$extension;
            $folderpath  = 'uploads/obqvi/'.$ad->uid . '/';
            $test =  $file->move($folderpath , $fileName);
            $filepath =  $folderpath . $fileName;

            $dbimages = new AdImage();
            $dbimages->ad_id = $ad->id;
            $dbimages->filepath = $filepath;

            $dbimages->save();


            $counter++;



        }
        return  back()->with('success','Успешно Обновяване');

    }
    else {
        return back()->with('info','Не сте въвели Данни');
    }

}

    public function editimages($id) {
        $ad = Ad::find($id);

        $imagescount = $ad->images->count();

        return view('ads.editimages',compact('ad','imagescount'));
    }



    public function single($id)
    {
        $ad = Ad::find($id);
//        dd($ad);
        $ad->views += 1;
        $ad->save();

        $isfavorite = false;
        $favoriteads = [];
        if($user = Auth::user())
        {
            $user = Auth::user();
            // do what you need to do

            $favoriteads = FavoriteAds::with('user')
                ->where('ad_id','=',$ad->id)
                ->where('user_id','=',$user->id)->get();



            if($favoriteads->isEmpty()) {

            }
            else {
                $isfavorite = true;
            }
        }

        return view('ads.single',compact('ad','isfavorite','favoriteads'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $regions = Region::all();
        $adtypes = AdType::all();
        $adconditions = AdCondition::all();
        $addeliveries = AdDelivery::all();
        $ad = Ad::find($id);
        return view('ads.edit',compact('ad','adtypes','regions','adconditions','addeliveries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {

        $ad = Ad::find($id);
        $ad->adtype_id = $request['adtype_id'];
        $ad->title = $request['title'];
        $ad->description = $request['description'];
        $ad->price = $request['price'];

        $ad->adcondition_id = $request['adcondition_id'];
        $ad->addelivery_id = $request['addelivery_id'];
        $ad->region_id = $request['region_id'];

        $ad->accept_offers = $request['accept_offer'];
        $ad->is_active = $request['is_active'];

        $ad->save();

        return back()->with('success','Успешна Редакция');



    }

    public  function deleteimage($id) {
        $image = AdImage::find($id);
        $path = $image->filepath;
        unlink($path);
        $image->delete();

        return back()->with('message','Изображението е успешно изтрито');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ad  $ad
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ad $ad)
    {
        //
    }


}

app/Http/Controllers/Admin/AdController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Ad;
use App\AdDelivery;
use App\AdType;
use App\AdCondition;
use App\Region;
use App\AdImage;
use Illuminate\Support\Facades\File;
class AdController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $deliveries = AdDelivery::all();
        $conditions = AdCondition::all();
        $types = AdType::all();
        $regions = Region::all();
        $ads = Ad::with('type','user','delivery','condition','region','category','images')
            ->orderBy('created_at','desc')
            ->get();


        return view('admin.ads.index',compact('ads','deliveries','conditions','types','regions'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $deliveries = AdDelivery::all();
        $conditions = AdCondition::all();
        $types = AdType::all();
        return view('admin.ads.create',compact('deliveries','conditions','types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ad = new Ad();

       return redirect()->route('admin.ad.index')->with('message','Успешно Добавяне');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $conditions = AdCondition::all();
        $types = AdType::all();
        $ad = Ad::find($id);



        $regions = Region::all();
        $deliveries = AdDelivery::all();
        $categories = Category::all();
//        dd($ad->delivery);
        return view('admin.ads.edit',
            compact('ad','conditions','types','regions','deliveries','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ad = Ad::find($id);
       $ad->update($request->all());
        return redirect()->route('admin.ad.index')->with('success','Успешна Редакция');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ad  = Ad::find($id);
        $adimages = $ad->images;
        if($adimages) {
            $imagecount = 0;
            foreach ($adimages as $image) {

                $path = $image->filepath;

                $image->delete();
                if(file_exists($path)) {
                    if($path == 'noimage-small.png') {

                    }
                    else {
                        @unlink($path);
                        $imagecount++;
                    }


                }
            }
        }
        $ad->delete();

        return redirect()->route('admin.ad.index')
            ->with('success','Изтрита обява  + ' . $imagecount . ' Изображения от базата и файловете');

    }
}

resources/views/admin/ads/create.blade.php
@extends('admin.layouts.app')
@section('title','Създаване на новa Обява')

@section('content')
    <form action="{{route('admin.ad.store')}}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('post')
        <div class="row">
            <div class="col-lg-5">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Заглавие</h3>
                    </div>
                    <div class="card-body">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" value="" name="title">
                        </div>
                    </div>


                </div>
            </div>
            <div class="col-lg-7">

                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Описание на Обявата</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <textarea class="form-control" rows="3" name="description"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Допълнително</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label for="form-controlactive">Активна?</label>
                                    <select class="form-control text-info" id="form-controlactive" name="is_active">
                                        <option value="0">Не</option>
                                        <option value="1" >Да</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label for="form-controlactive">Състояние?</label>
                                    <select class="form-control text-info" id="form-controlactive" name="adcondition_id">
                                        @forelse($conditions as $condition)
                                            <option value="{{$condition->id}}" >{{$condition->name}}</option>
                                        @empty
                                            Няма
                                        @endforelse

                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label for="form-controlactive">Тип?</label>
                                    <select class="form-control text-danger" id="form-controlactive" name="adtype_id">
                                        @forelse($types as $type)
                                            <option value="{{$type->id}}" >{{$type->name}}</option>
                                        @empty
                                            <option value="" >Няма Създаден Тип</option>
                                        @endforelse

                                    </select>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-success">Създаване</button>
        </div>
    </form>

@stop


@section('scripts')


@endsection

resources/views/admin/ads/index.blade.php
@extends('admin.layouts.app')
@section('title','Всички Обяви')

@section('content')
    <div class="card-body table-responsive p-0">
        <a href="{{route('admin.ad.create')}}">
            <button type="button" class="btn btn-info btn-sm">Добавяне на нова Обява</button>
        </a>
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Заглавие</th>
                <th>Потребител</th>
                <th>Дата</th>
                <th>Активна?</th>
                <th>Изображения?</th>
                <th>Категория</th>

                <th>Опции</th>
            </tr>
            @forelse($ads as $ad)
                <tr>
                    <td>{{$ad->id}}</td>
                    <td>{{$ad->title}}</td>

                    <td>
                        @if($ad->user)
                            {{$ad->user->username}}
                        @else
                            Няма
                        @endif
                    </td>
                    <td>{{$ad->created_at->diffForHumans()}}</td>
                    <td>
                        @if($ad->is_active)
                            <button type="button" class="btn btn-success btn-sm">Да</button>
                            @else
                            <button type="button" class="btn btn-danger btn-sm">Не</button>
                        @endif
                    </td>
                    <td>
                        @if ($ad->images)
                            {{$ad->images->count()}}
                            @else
                            Няма
                        @endif
                    </td>
                    <td>
                        @if($ad->category)
                        {{$ad->category->name}}
                            @else
                        Няма
                            @endif
                    </td>

                    <td>
                        <a href="{{route('admin.ad.edit', $ad->id)}}"><button class="btn btn-primary btn-sm">Редакция/Преглед</button></a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger-{{$ad->id}}">
                            Изтриване
                        </button>
                    </td>
                </tr>
                <div class="modal fade" id="modal-danger-{{$ad->id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-danger">
                            <div class="modal-header">
                                <h4 class="modal-title">Изтриване на Обява?</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <form action="{{route('admin.ad.destroy',$ad->id)}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Изтриване</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Отказ</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>

            @empty
                <hr>
                Няма добавени Обяви Все Още
            @endforelse
            </tbody>
        </table>
    </div>

    <!-- /.modal -->
@stop