routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




/*
 * Front End Routes
 */
Route::get('/search/','SearchController@index')->name('search.index');

Route::get('/contact/','PageController@contact')->name('contact.index');
Route::get('/usloviq/','PageController@usloviq')->name('usloviq.index');
Route::get('/gdpr/','PageController@gdpr')->name('gdpr.index');

Route::get('/ads/gradove/','RegionController@index')->name('region.index');
Route::get('/ads/gradove/{id}/{slug}','RegionController@single')->name('region.single');
Route::get('/','HomeController@index')->name('home');
Route::get('/ads','AdController@index')->name('ad.index');

Route::get('/ads/kategorii','CategoryController@index')->name('category.index');
Route::get('/ads/kategorii/{id}/{slug}', 'CategoryController@single')->name('category.single');
Route::get('/ads/tip/{id}/{slug}', 'AdTypeController@index')->name('adtype.single');

Route::get('users', 'UserController@index')->name('users.index');
Route::get('users/ads/{id}', 'UserController@publishedads')->name('users.publishedads');

Route::get('users/{id}', 'UserController@single')->name('users.single');
Route::get('ratings/user/{id}', 'RatingController@single')->name('ratings.single');

Route::get('/ads/{id}/{catslug}/{uid}','AdController@single')->name('ad.single');




//blog

Route::get('articles', 'BlogArticleController@index')->name('articles.index');
Route::get('articles/read/{article_id}/{category_slug}/{article_slug}/', 'BlogArticleController@single')->name('blogarticles.single');

Route::get('articles/category/{category_id}/{category-slug}', 'BlogCategoryController@single')->name('blogcategories.single');


//end blog


Route::group(['middleware' => 'auth'], function() {
    //Auth routes for the front end
    Route::post('dashboard/edit', 'DashboardController@storeprofile')->name('store.profile');
    Route::get('ads/create', 'AdController@create')->name('ad.create');
    Route::post('ads/store', 'AdController@store')->name('ad.store');
    Route::get('ads/edit/{id}', 'AdController@edit')->name('ad.edit')->middleware('isYourAd');
    Route::get('ads/editimages/{id}', 'AdController@editimages')->name('ad.editimages')->middleware('isYourAd');
    Route::post('ads/update/{id}', 'AdController@update')->name('ad.update')->middleware('isYourAd');
    Route::post('ads/deleteimage/{id}', 'AdController@deleteimage')->name('adimage.delete')->middleware('isYourAd');;
    Route::post('ads/updateimage/{id}', 'AdController@updateimage')->name('adimage.update')->middleware('isYourAd');;


    Route::post('favoriteads/{ad_id}', 'FavoriteAdsController@store')->name('favorite.store');
    Route::post('deletefavoriteads/{id}', 'FavoriteAdsController@destroy')->name('favorite.destroy');

    Route::get('dashboard/favorites', 'FavoriteAdsController@index')->name('dashboard.favorites');
    Route::get('report/{id}', 'ReportController@create')->name('report.create');
    Route::post('report/{id}', 'ReportController@store')->name('report.store');
//    Route::get('uploadimage', 'AdController@mainimage')->name('ad.mainimage');
    Route::get('offer/{ad_id}', 'OfferController@create')->name('offer.create');
    Route::post('offer/{ad_id}', 'OfferController@store')->name('offer.store');
    Route::get('offers/', 'OfferController@index')->name('offer.index');
    Route::get('offer/read/{id}', 'OfferController@single')->name('offer.single');
    Route::get('dashboard/myads', 'DashboardController@myads')->name('dashboard.myads');
    Route::get('messages', 'MessageController@index')->name('messages.index');
    Route::get('messages/read/{id}', 'MessageController@single')->name('messages.single');
    Route::post('messages/insert/{id}', 'MessageController@insert')->name('messages.insert');
    Route::post('messages/compose/{adid}/{sender_id}/{receiver?}', 'MessageController@create')->name('messages.create');
    Route::get('messages/create/{adid}/{sender_id}/{accept?}', 'MessageController@compose')->name('messages.compose');
    Route::post('offerreject/{id}', 'OfferController@reject')->name('offer.reject');
    Route::post('acceptoffer/{id}', 'OfferController@accept')->name('offer.accept');
    Route::get('dashboard/changepassword', 'UserController@changepassword')->name('user.changepassword');
    Route::get('dashboard/editprofile', 'DashboardController@editprofile')->name('dashboard.editprofile');
    Route::post('dashboard/changepassword', 'UserController@updatepassword')->name('dashboard.updatepassword');
    Route::get('offer/activeoffers/{id}', 'OfferController@activesingle')->name('offer.activesingle');
    Route::post('offer/activeoffers/{id}', 'OfferController@finishoffer')->name('offer.finishoffer');

    Route::post('/ratings/{id}/','RatingController@store')->name('rating.store');






});
Auth::routes(['verify' => true]);






Auth::routes();

Route::get('/blog', function () {
    return view('blog.index');
});

Route::get('logout', 'Auth\LoginController@logout');


//Auth::routes(['verify' => true]);

//Route::get('/home', 'HomeController@index')->name('home');

/*
 * admin routes
 */



Route::namespace('Admin')->prefix('panel')->name('admin.')->middleware('admin')->group(function () {

    Route::resource('region','RegionController');
    Route::resource('adtype','AdTypeController');
    Route::resource('ad','AdController');
    Route::resource('adcondition','AdConditionController');
    Route::resource('addelivery','AdDeliveryController');
    Route::resource('ad','AdController');
    Route::resource('category','CategoryController');
    Route::resource('settings','SettingsController');
    Route::resource('messages','MessageController');
    Route::resource('reports','ReportController');
    Route::resource('blogarticles','BlogArticleController');
    Route::resource('blogcategories','BlogCategoryController');
    Route::resource('statictexts','StaticTextController');
    Route::resource('pages','PagesController');
    Route::resource('users','UserController');
    Route::resource('offers','OfferController');
    Route::resource('ratings','RatingController');
    Route::get('/panel', function () {
        return view('admin.layouts.app');
    })->name('panel.welcome');



});

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{

    protected $guarded = [];


    public function  users() {
        return $this->hasMany('App\User');
    }

    public function ads() {
        return $this->hasMany('App\Ad');

    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Region;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $regions = Region::with('users')->get();
//        dd($regions);
        return view('admin.region.index',compact('regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.region.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $region = new Region();
        $region->name= $request['name'];
        $region->slug= Str::slug($request['name'],'-');
        $region->seo_title = $request['seo_title'];
        $region->seo_description = $request['seo_description'];
        $region->save();
        return redirect()->route('admin.region.index')->with('success','Успешно Добавяне на Област');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $region = Region::find($id);
        return view('admin.region.edit',compact('region'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Region::find($id)->update($request->all());
        return redirect()->route('admin.region.index')->with('success','Успешно Редактиране на Област');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $region = Region::find($id);
        $region->delete();
        return redirect()->route('admin.region.index')->with('success','Успешно Изтриване на Област');
    }
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Region;
use Illuminate\Http\Request;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $regions = Region::with('ads')->paginate(8);
        return view('region.index',compact('regions'));

    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Region  $region
     * @return \Illuminate\Http\Response
     */
    public function single($id,$slug)
    {

     $region = Region::find($id);
     $regionads = $region->ads()->paginate(16);



        return view('region.single',compact('region','regionads'));

    }


}

resources/views/admin/region/create.blade.php
@extends('admin.layouts.app')
@section('title','Създаване на нова Област')

@section('content')
    <form action="{{route('admin.region.store')}}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('post')
        <div class="row">
            <div class="col-lg-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Области/ Региони - Редакция</h3>
                    </div>
                    <div class="card-body">
                                <p class="text-sm">Име ( slug-a се генерира автоматично, след това може да се редактира ако не е удачен</p>
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" value="" name="name">
                                </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">

                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">SEO Информация</h3>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-8">
                            <p class="text-sm">SEO Тайтъл (около 60 символа - може и ASCII икони/символи - визулизират се от гугъл в търсачката</p>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="" name="seo_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <p class="text-sm">SEO Описание - не повече от 160, но гугъл показва около 115 на мобилни</p>
                            <textarea class="form-control" rows="3" name="seo_description"></textarea>
                        </div>
                    </div>

                </div>
            </div>
            <button type="submit" class="btn btn-block btn-success">Създаване</button>
        </div>
    </form>

@stop


@section('scripts')


@endsection

resources/views/admin/region/edit.blade.php
@extends('admin.layouts.app')
@section('title','Създаване на нова Област')

@section('content')
    <form action="{{route('admin.region.update',$region->id)}}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('put')
        <div class="row">
            <div class="col-lg-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Области/ Региони - Редакция</h3>
                    </div>
                    <div class="card-body">

                        <div class="input-group mb-3">
                            <p class="mr-4">Име на Област</p>
                            <input type="text" class="form-control" value="{{$region->name}}" name="name">
                        </div>
                        <div class="input-group mb-3 ">
                            <p class="mr-4">SEO slug</p>
                            <input type="text" class="form-control" value="{{$region->slug}}" name="name">
                        </div>
                        <hr>

                        <div class="input-group mb-3">
                            <p class="mr-4">SEO Тайтъл </p>
                            <input type="text" class="form-control" value="" name="seo_title">
                        </div>
                        <div class="form-group">
                            <p class="text-sm">SEO Описание</p>
                            <textarea class="form-control" rows="3" name="seo_description"></textarea>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-block btn-success">Редакция</button>
        </div>
    </form>

@stop


@section('scripts')


@endsection

resources/views/admin/region/index.blade.php
@extends('admin.layouts.app')
@section('title','Области')

@section('content')
    <div class="card-body table-responsive p-0">
        <a href="{{route('admin.region.create')}}">
            <button type="button" class="btn btn-info btn-sm" >
                Нова Област
            </button></a>
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Име</th>
                <th>slug</th>
                <th>Брой Обяви</th>
                <th>Брой Потребители</th>
                <th>Опции</th>
            </tr>

            @forelse($regions as $region)

                <tr>
                    <td>{{$region->id}}</td>
                    <td>{{$region->name}}</td>
                    <td>{{$region->slug}}</td>
                    <td>TODO</td>
                    <td>
                        @if($region->users)
                        {{$region->users->count()}}
                            @else няма
                            @endif
                    </td>
                    <td>
                        <a href="{{route('admin.region.edit', $region->id)}}"><button class="btn btn-primary btn-sm">Редакция/Преглед</button></a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger-{{$region->id}}">
                            Изтриване
                        </button>
                    </td>
                </tr>
                <hr>
                <div class="modal fade" id="modal-danger-{{$region->id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-danger">
                            <div class="modal-header">
                                <h4 class="modal-title">Изтриване на Област?</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <form action="{{route('admin.region.destroy',$region->id)}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Изтриване</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Отказ</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
            @empty
                <hr>
               Няма добавени Области
            @endforelse








            </tbody>
        </table>
    </div>

    <!-- /.modal -->
@stop