routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




/*
 * Front End Routes
 */
Route::get('/search/','SearchController@index')->name('search.index');

Route::get('/contact/','PageController@contact')->name('contact.index');
Route::get('/usloviq/','PageController@usloviq')->name('usloviq.index');
Route::get('/gdpr/','PageController@gdpr')->name('gdpr.index');

Route::get('/ads/gradove/','RegionController@index')->name('region.index');
Route::get('/ads/gradove/{id}/{slug}','RegionController@single')->name('region.single');
Route::get('/','HomeController@index')->name('home');
Route::get('/ads','AdController@index')->name('ad.index');

Route::get('/ads/kategorii','CategoryController@index')->name('category.index');
Route::get('/ads/kategorii/{id}/{slug}', 'CategoryController@single')->name('category.single');
Route::get('/ads/tip/{id}/{slug}', 'AdTypeController@index')->name('adtype.single');

Route::get('users', 'UserController@index')->name('users.index');
Route::get('users/ads/{id}', 'UserController@publishedads')->name('users.publishedads');

Route::get('users/{id}', 'UserController@single')->name('users.single');
Route::get('ratings/user/{id}', 'RatingController@single')->name('ratings.single');

Route::get('/ads/{id}/{catslug}/{uid}','AdController@single')->name('ad.single');




//blog

Route::get('articles', 'BlogArticleController@index')->name('articles.index');
Route::get('articles/read/{article_id}/{category_slug}/{article_slug}/', 'BlogArticleController@single')->name('blogarticles.single');

Route::get('articles/category/{category_id}/{category-slug}', 'BlogCategoryController@single')->name('blogcategories.single');


//end blog


Route::group(['middleware' => 'auth'], function() {
    //Auth routes for the front end
    Route::post('dashboard/edit', 'DashboardController@storeprofile')->name('store.profile');
    Route::get('ads/create', 'AdController@create')->name('ad.create');
    Route::post('ads/store', 'AdController@store')->name('ad.store');
    Route::get('ads/edit/{id}', 'AdController@edit')->name('ad.edit')->middleware('isYourAd');
    Route::get('ads/editimages/{id}', 'AdController@editimages')->name('ad.editimages')->middleware('isYourAd');
    Route::post('ads/update/{id}', 'AdController@update')->name('ad.update')->middleware('isYourAd');
    Route::post('ads/deleteimage/{id}', 'AdController@deleteimage')->name('adimage.delete')->middleware('isYourAd');;
    Route::post('ads/updateimage/{id}', 'AdController@updateimage')->name('adimage.update')->middleware('isYourAd');;


    Route::post('favoriteads/{ad_id}', 'FavoriteAdsController@store')->name('favorite.store');
    Route::post('deletefavoriteads/{id}', 'FavoriteAdsController@destroy')->name('favorite.destroy');

    Route::get('dashboard/favorites', 'FavoriteAdsController@index')->name('dashboard.favorites');
    Route::get('report/{id}', 'ReportController@create')->name('report.create');
    Route::post('report/{id}', 'ReportController@store')->name('report.store');
//    Route::get('uploadimage', 'AdController@mainimage')->name('ad.mainimage');
    Route::get('offer/{ad_id}', 'OfferController@create')->name('offer.create');
    Route::post('offer/{ad_id}', 'OfferController@store')->name('offer.store');
    Route::get('offers/', 'OfferController@index')->name('offer.index');
    Route::get('offer/read/{id}', 'OfferController@single')->name('offer.single');
    Route::get('dashboard/myads', 'DashboardController@myads')->name('dashboard.myads');
    Route::get('messages', 'MessageController@index')->name('messages.index');
    Route::get('messages/read/{id}', 'MessageController@single')->name('messages.single');
    Route::post('messages/insert/{id}', 'MessageController@insert')->name('messages.insert');
    Route::post('messages/compose/{adid}/{sender_id}/{receiver?}', 'MessageController@create')->name('messages.create');
    Route::get('messages/create/{adid}/{sender_id}/{accept?}', 'MessageController@compose')->name('messages.compose');
    Route::post('offerreject/{id}', 'OfferController@reject')->name('offer.reject');
    Route::post('acceptoffer/{id}', 'OfferController@accept')->name('offer.accept');
    Route::get('dashboard/changepassword', 'UserController@changepassword')->name('user.changepassword');
    Route::get('dashboard/editprofile', 'DashboardController@editprofile')->name('dashboard.editprofile');
    Route::post('dashboard/changepassword', 'UserController@updatepassword')->name('dashboard.updatepassword');
    Route::get('offer/activeoffers/{id}', 'OfferController@activesingle')->name('offer.activesingle');
    Route::post('offer/activeoffers/{id}', 'OfferController@finishoffer')->name('offer.finishoffer');

    Route::post('/ratings/{id}/','RatingController@store')->name('rating.store');






});
Auth::routes(['verify' => true]);






Auth::routes();

Route::get('/blog', function () {
    return view('blog.index');
});

Route::get('logout', 'Auth\LoginController@logout');


//Auth::routes(['verify' => true]);

//Route::get('/home', 'HomeController@index')->name('home');

/*
 * admin routes
 */



Route::namespace('Admin')->prefix('panel')->name('admin.')->middleware('admin')->group(function () {

    Route::resource('region','RegionController');
    Route::resource('adtype','AdTypeController');
    Route::resource('ad','AdController');
    Route::resource('adcondition','AdConditionController');
    Route::resource('addelivery','AdDeliveryController');
    Route::resource('ad','AdController');
    Route::resource('category','CategoryController');
    Route::resource('settings','SettingsController');
    Route::resource('messages','MessageController');
    Route::resource('reports','ReportController');
    Route::resource('blogarticles','BlogArticleController');
    Route::resource('blogcategories','BlogCategoryController');
    Route::resource('statictexts','StaticTextController');
    Route::resource('pages','PagesController');
    Route::resource('users','UserController');
    Route::resource('offers','OfferController');
    Route::resource('ratings','RatingController');
    Route::get('/panel', function () {
        return view('admin.layouts.app');
    })->name('panel.welcome');



});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Category extends Model
{
    protected $guarded = [];


    /**
     * Get the Categories associated with the parent's `id`
     */
    public function children()
    {
        return $this->hasMany('App\Category', 'parent_id', 'id');
    }

    /**
     * Get the parent associated with the Category`s parent_id`
     */
    public function parent()
    {
        return $this->belongsTo('App\Category','parent_id');
    }


    public function ads() {
        return $this->hasMany('App\Ad');
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('parent')->get();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.categories.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();
        $category->name = $request['name'];
        $category->slug = Str::slug($request['name'],'-');
        $category->seo_title = $request['seo_title'];
        $category->seo_description = $request['seo_description'];
        $category->parent_id = $request['parent_id'];
        $category->icon = $request['icon'];
        $category->save();
        return redirect()->route('admin.category.index')->with('success','Успешно добавяне на  Категория');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $category = Category::find($id);
        return view('admin.categories.edit',compact('categories','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request['name'];
        $category->slug = $request['slug'];
        $category->seo_title = $request['seo_title'];
        $category->seo_description = $request['seo_description'];
        $category->parent_id = $request['parent_id'];
        $category->icon = $request['icon'];

        $category->save();
        return redirect()->route('admin.category.index')->with('success','Успешно добавяне на  Категория');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        return redirect()->route('admin.category.index')->with('success','Успешно Изтриване на Категория');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('parent','children')->get();
        return view('categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function single($id, $slug)
    {
        $category = Category::find($id);
        $ads = Category::find($id)->ads()->where('is_active',true)->orderBy('created_at','desc')->paginate(15);
        return view('categories.single',compact('ads','category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title','Създаване на нова Категория')

@section('content')
    <form action="{{route('admin.category.store')}}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('post')
        <div class="row">
            <div class="col-lg-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Категория</h3>
                    </div>
                    <div class="card-body">
                        <p class="text-sm">Име</p>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" value="" name="name">
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="text-sm">Иконка</p>
                        <div class="">
                            <span class="input-group-addon"><i class="fa fa-check"></i></span>
                            <hr>

                            <input type="text" class="form-control icp icp-auto my" value="" name="icon">
                        </div>

                    </div>

                    <div class="card-body">
                        <p class="text-sm">Родител</p>
                        <div class="form-group">
                            <select class="form-control" id="" name="parent_id">
                                <option value="0">-без Родител</option>
                                @forelse($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @empty
                                    <p>Няма добавени</p>
                                @endforelse
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">SEO Информация</h3>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-8">
                            <p class="text-sm">SEO Тайтъл (около 60 символа - може и ASCII икони/символи - визулизират се от гугъл в търсачката</p>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="" name="seo_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <p class="text-sm">SEO Описание - не повече от 160, но гугъл показва около 115 на мобилни</p>
                            <textarea class="form-control" rows="3" name="seo_description"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-block btn-success">Създаване</button>
        </div>
    </form>

@stop


@section('scripts')

    <script src="{{asset('admin/iconpicker/dist/js/fontawesome-iconpicker.min.js')}}"></script>
    <script>
        $('.my').iconpicker();

    </script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('admin/iconpicker/dist/css/fontawesome-iconpicker.css')}}" type="text/css">
    <style>
        .fade.in{
            opacity: 1;
        }
    </style>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('title','Редакция на Категория')

@section('content')
    <form action="{{route('admin.category.update',$category->id)}}" method="POST" enctype="multipart/form-data">
        @csrf()
        @method('put')
        <div class="row">
            <div class="col-lg-6">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Име</h3>
                    </div>
                    <div class="card-body">
                        <p class="text-sm">Име  ( slug-a се генерира автоматично, след това може да се редактира ако не е удачен</p>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" value="{{$category->name}}" name="name">
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="text-sm">Иконка</p>
                        <div class="">
                            <span class="input-group-addon"><i class="{{$category->icon}}"></i></span>
                            <hr>

                            <input type="text" class="form-control icp icp-auto my"  name="icon" value="{{$category->icon}}">
                        </div>

                    </div>

                    <div class="card-body">
                        <p class="text-sm">slug</p>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" value="{{$category->slug}}" name="slug">
                        </div>
                    </div>
                    <div class="card-body">
                        <p class="text-sm">Родител</p>
                        <div class="form-group">
                            <select class="form-control" id="" name="parent_id">
                                <option value="0">-без Родител</option>
                                @forelse($categories as $categoryfor)
                                    @if($categoryfor->id == $category->id)
                                    @else
                                        <option value="{{$categoryfor->id}}
                                        {{$categoryfor->parent_id == $categoryfor->id ? 'selected' : ''}}">{{$categoryfor->name}}</option>
                                    @endif

                                @empty
                                    <p>Няма добавени</p>
                                @endforelse
                            </select>
                        </div>
                    </div>

            </div>
            </div>

            <div class="col-lg-6">

                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">SEO Информация</h3>
                    </div>
                    <div class="card-body">
                        <div class="col-lg-8">
                            <p class="text-sm">SEO Тайтъл (около 60 символа - може и ASCII икони/символи - визулизират се от гугъл в търсачката</p>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="{{$category->seo_title}}" name="seo_title">
                            </div>
                        </div>
                        <div class="form-group">
                            <p class="text-sm">SEO Описание - не повече от 160, но гугъл показва около 115 на мобилни</p>
                            <textarea class="form-control" rows="3" name="seo_description">{{$category->seo_description}}</textarea>
                        </div>
                    </div>

                </div>
            </div>
            <button type="submit" class="btn btn-block btn-success">Редакция</button>
        </div>
    </form>


@stop


@section('scripts')

    <script src="{{asset('admin/iconpicker/dist/js/fontawesome-iconpicker.min.js')}}"></script>
    <script>
        $('.my').iconpicker();

    </script>

@endsection


@section('css')
    <link rel="stylesheet" href="{{asset('admin/iconpicker/dist/css/fontawesome-iconpicker.css')}}" type="text/css">
    <style>
        .fade.in{
            opacity: 1;
        }
    </style>

@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title','Категории ( на обявите )')

@section('content')
    <div class="card-body table-responsive p-0">
        <a href="{{route('admin.category.create')}}">
            <button type="button" class="btn btn-info btn-sm">Създаване на Категория</button>
        </a>
        <table class="table table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <th>Име</th>
                <th>slug</th>
                <th>родител</th>
                <th>иконка</th>
                <th>Опции</th>
            </tr>
            @forelse($categories as $category)
                <tr>
                    <td>{{$category->id}}</td>
                    <td>{{$category->name}}</td>
                    <td>{{$category->slug}}</td>
                    <td>
                       @if($category->parent)
                            {{$category->parent->name}}
                           @else
                           Няма
                        @endif
                    </td>
                    <td>
                        @if($category->icon)
                            <i class="{{$category->icon}}"></i>
                        @else
                            Няма
                        @endif
                    </td>


                    <td>
                        <a href="{{route('admin.category.edit', $category->id)}}"><button class="btn btn-primary btn-sm">Редакция/Преглед</button></a>
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-danger-{{$category->id}}">
                            Изтриване
                        </button>
                    </td>
                </tr>
                <div class="modal fade" id="modal-danger-{{$category->id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-danger">
                            <div class="modal-header">
                                <h4 class="modal-title">Изтриване на Тип?</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <form action="{{route('admin.category.destroy',$category->id)}}" method="POST">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Изтриване</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Отказ</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>

            @empty
                <hr>
                Няма добавени Категории
            @endforelse
            </tbody>
        </table>
    </div>

    <!-- /.modal -->
@stop